baseurl = "https://example.com"
languageCode = "en-us"
title = "David Reinstein"
theme = "researcher"
googleAnalytics = ""
disqusShortname = ""
math = true # Enable Katex globally

[permalinks]
    post = "/:year/:month/:day/:slug/"
    "/" = "/:filename"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "CV"
    url = "/vitae/"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/daaronr"
[[menu.main]]
    name = "Scholar"
    url = "https://scholar.google.com/citations?user=ZGVPBmUAAAAJ&hl=en&oi=ao"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/GivingTools"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico" # Icon for chrome tabs
